### ISSUE TITLE
Title & Size 

### ISSUE THREAD

**Issue by jaikishantulswani** [DriftSec/httprobex#1]
Hi @DriftSec Can you please update this useful tool as it fails in some cases to fetch `Title and Size`, it would be good if you also implement a `follow-redirect` switch

**Comment by DriftSec** [comment]
I added a -r flag to follow redirects.  The title and size issue will need some testing. do you have a specific scenario or url that is resulting in a failure to get title or size so i can debug?

**Comment by jaikishantulswani** [comment]
Hi @DriftSec thank you so much for this super quick update, also waiting for this tool to also have features to get details like `cname,extract tls domains,save response` and also for scanning purpose having portscan flags like `medium, large and xlage` then tools becomes much useful in more cases.

Thank You

**Comment by jaikishantulswani** [comment]
Hi @DriftSec Any updates on this ?

**Comment by DriftSec** [comment]
There are port flags like you mentioned. I.e. -p large.  As for adding the other features, im trying to keep additional functionality minimal.

**Comment by jaikishantulswani** [comment]
@DriftSec Indeed but at least can you please add these `web-server,cname,extract tls domains,save response`

**Comment by jaikishantulswani** [comment]
@DriftSec Any update ?

**Comment by jaikishantulswani** [comment]
@DriftSec Waiting for this.

**Comment by jaikishantulswani** [comment]
@DriftSec

**Comment by jaikishantulswani** [comment]
@DriftSec

**Comment by thelikes** [comment]
@DriftSec Any update ?

**Comment by jaikishantulswani** [comment]
@DriftSec Any update on this.

**Comment by thelikes** [comment]
@DriftSec seriously man, get off your bum

**Comment by jaikishantulswani** [comment]
@DriftSec Getting issue while using `-r` flag

```
goroutine 19 [running]:
main.GetDetails(0xc0002b2100, 0xc0001345a0)
	/root/go_projects/src/github.com/DriftSec/x/httprobex/main.go:265 +0x32b
main.isListening(0x0?, {0xc0002d4138?, 0x0?}, {0x68e5de?, 0x0?})
	/root/go_projects/src/github.com/DriftSec/x/httprobex/main.go:285 +0x192
main.main.func2()
	/root/go_projects/src/github.com/DriftSec/x/httprobex/main.go:115 +0xf8
created by main.main
	/root/go_projects/src/github.com/DriftSec/x/httprobex/main.go:110 +0x516
```
